name: "Deploy"

on:
  push:
    branches:
      - v2.1

jobs:
  job-1:
    name: Publish to GitHub and PowerShell Gallery
    runs-on: ubuntu-latest
    #if: "contains(github.event.head_commit.message, ':shipit:')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1

      - name: Set environment variables
        run: |
          $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
          @(
            "GH_USERNAME={0}" -f $Username
            "GH_PROJECTNAME={0}" -f $ProjectName
          ) | Add-Content -Path $env:GITHUB_ENV
        shell: pwsh

      - name: Print defined environment variables
        run: |
          Write-Output $GH_USERNAME
          Write-Output $GH_PROJECTNAME
        shell: pwsh

      - name: Test Path
        run: |
          dir (join-path $env:GITHUB_WORKSPACE -childpath module)
          write-host "#### ----------- ####"
        shell: pwsh

      - name: Install dependent modules
        run: |
          $Modules = @(
            "Pester"
            "InvokeBuild"
          )
          #Install-Module -Name $Modules -Scope "CurrentUser" -ErrorAction "Stop"
          Get-module Pester -list
        shell: pwsh

      - name: Run Pester Tests
        run: |
          Import-Module (join-path $env:GITHUB_WORKSPACE -childpath 'module/PSLiteDB.psd1')
          Invoke-Pester -path (join-path $env:GITHUB_WORKSPACE -childpath 'tests/v5.tests.ps1') -pass | Export-CliXml -Path pester_test_result.xml
        shell: pwsh

      - name: test module
        id: test_module
        uses: zyborg/pester-tests-report@v1
        with:
          test_results_path: pester_test_result.xml
          report_name: module_tests
          report_title: $env:GH_PROJECTNAME Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_token: ${{ secrets.GIST_TOKEN }}
      - name: dump test results
        shell: pwsh
        run: |
            Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
            Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
            Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'