name: "CI"

on:
  push:
    branches:
      - v2.2

jobs:
  job-1:
    name: Publish to GitHub and PowerShell Gallery
    runs-on: ubuntu-latest
    #if: "contains(github.event.head_commit.message, ':shipit:')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1

      - name: Set environment variables
        run: |
          $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
          @(
            "GH_USERNAME={0}" -f $Username
            "GH_PROJECTNAME={0}" -f $ProjectName
          ) | Add-Content -Path $env:GITHUB_ENV
        shell: pwsh

      - name: Run Pester Tests
        run: |
          Import-Module (join-path $env:GITHUB_WORKSPACE -childpath 'module/PSLiteDB.psd1')
          Invoke-Pester -path (join-path $env:GITHUB_WORKSPACE -childpath 'tests/v5.tests.ps1') -pass -Outputfile pester_test_result.xml -OutputFormat NUnitXml
        shell: pwsh

      - name: test module
        id: test_module
        uses: zyborg/pester-tests-report@v1
        with:
          test_results_path: pester_test_result.xml
          report_name: ${{ runner.os }}
          report_title: Pester Results on ${{ runner.os }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_name: ${{ runner.os }}
          gist_badge_label: Tests %PassedCount%/%TotalCount%
