name: "CD"

on:
  push:
    branches:
      - master

jobs:
  job-1:
    name: Deploy
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'shipit')"
    steps:
      - name: Publish Module to PowerShell Gallery
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.PSGALLERY}}