name: "CD"

on:
  push:
    branches:
      - master

jobs:
  job-1:
    name: Deploy
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'shipit')"
    steps:
      - name: Step-1 Clone Repository
        uses: actions/checkout@v2.4.0

      - name: Step-2 Publish Module to PowerShell Gallery
        run: |
          Write-Host "Begin publishing module: $pwd $PWD"
          ./build/publish.ps1 -PSGalleryApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh