name: "Deploy"

on:
  push:
    branches:
      - master
      - v2.2

jobs:
  job-1:
    name: Publish to GitHub and PowerShell Gallery
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'iftest')"
    steps:
      - name: Test shipit
        run: |
          write-host "#### ----------- ####"
          write-host "Testing action based on if condition 'iftest'"
        shell: pwsh
